---
layout: post
title: 3. 반복문과 배열 그리고 예외 처리
date: 2025-10-28 16:34:49 +0900
categories:
  - 개발
  - 자바
published: true
math: true
tags:
  - 자바
  - 반복문
  - 배열
  - 예외처리
---
## 3.7 자바의 예외 처리
### 예외(Exception)이란?
자바에서 오동작이나 결과의 악영향을 미칠 수 있는 실행 중 발생한 오류를 예외라고 한다. 문법에 맞지 않게 작성된 코드는 사전에 컴파일러에 의해 파일 오류로 걸러지지만, 예외는 사용자의 잘못된 입력에 의해 배열의 인덱스가 크기를 넘어가는 등, 예기치 못한 상황에 의해 프로그램 실행 중에 발생한다.

- 정수를 0으로 나누는 경우
- 배열의 크기보다 큰 인덱스로 배열의 원소를 접근하는 경우
- 존재하지 않는 파일을 읽으려고 하는 경우
- 정수 입력을 기다리는 코드가 실행되고 있을 때 사용자가 문자를 입력한 경우

위 같은 상황 같이 예외가 발생하면 자바 플랫폼이 가장 먼저 알게 되어, 현재 실행 중인 응용프로그램에게 예외를 전달한다. 만약 응용프로그램이 예외에 대처하는 코드를 가지고 있지 않다면 자바 플랫폼은 응용프로그램을 곧바로 종료시킨다.

### 예외 처리, try-catch-finally문

```java
try {
	예외가 발생할 가능성이 있는 실행분(try 블록)
} 
catch (처리할 예외 타입 선언) {
	예외 처리문 (catch 블록)
}
finally {
	예외 발생 여부와 상관 없이 무조건 실행되는 문장 (finally 블록, 생략 가능)
}
```

### 자바의 예외 클래스

| 예외 타입(예외 클래스)                  | 예외 발생 경우                                                              | 패키지       |
| ------------------------------ | --------------------------------------------------------------------- | --------- |
| ArithmeticException            | 정수를 0으로 나눌 때 발생                                                       | java.lang |
| NullPointerException           | null 레퍼런스를 참조할 때 발생                                                   | java.lang |
| ClassCastException             | 변환할 수 없는 타입으로 객체를 변환할 때 발생                                            | java.lang |
| OutOfMemoryException           | 메모리가 부족한 경우 발생                                                        | java.lang |
| ArrayIndexOutOfBoundsException | 배열의 범위를 벗어난 접근 시 발생                                                   | java.lang |
| IllgalArgumentException        | 잘못된 인자 전달 시 발생                                                        | java.lang |
| IOException                    | 입출력 동작 실패 또는 인터럽트 시 발생                                                | java.io   |
| NumberFormatException          | 문자열이 나타내는 숫자와 일치하지 않는 타입의 숫자로 변환 시 발생                                 | java.lang |
| InputMismatchException         | Scanner 클래스의 nextInt()를 호출하여 정수로 입력받고자 하였지만, 사용자가 'a'등과 같이 문자를 입력한 경우 | java.util |

### 예외 던지기
개발자가 직접 예외를 강제로 발생시킬수도 있다. 본인이 생각하기에 특정 조건이 에러라고 생각되면, 예외 객체를 던질 수 있다. throw 문을 사용하여 예외 객체를 던진다.

| **구분** | **throw (직접 던지기) **                | **throws (책임 전가 / 선언) **                 |
| ------ | ---------------------------------- | ---------------------------------------- |
| **역할** | 예외를 **발생시킴**                       | 예외가 발생**할 수 있음**을 선언                     |
| **위치** | 메서드 **내부 (body)** `{ }` 안          | 메서드 **선언부 (signature)**                  |
| **사용** | `throw new Exception();` (객체 인스턴스) | `void func() throws Exception;` (클래스 타입) |
| **비유** | (내가) 사고를 **일으킴**                   | (내가) "여기서 사고 날 수 있어!"라고 **경고판** 세우기      |
